#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Evanshenf
# SPDX-License-Identifier: BSD-3-Clause

"""Emit identity/phase stimuli for the independent C phase executor."""

from __future__ import annotations

import argparse
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import sys

from check_c42_claim_models import DEFAULT_MODEL_DIR, ModelError, build_model


TARGET_KINDS = {
    "field": "C42_STATE_TARGET_FIELD",
    "identity_edge": "C42_STATE_TARGET_IDENTITY_EDGE",
    "identity_domain": "C42_STATE_TARGET_IDENTITY_DOMAIN",
    "transition": "C42_STATE_TARGET_TRANSITION",
}
RULE_KINDS = {
    "exact": "C42_STATE_RULE_EXACT",
    "required_zero": "C42_STATE_RULE_REQUIRED_ZERO",
    "derived_equal": "C42_STATE_RULE_DERIVED_EQUAL",
    "equal": "C42_STATE_RULE_EQUAL",
    "stable": "C42_STATE_RULE_STABLE",
    "independent": "C42_STATE_RULE_INDEPENDENT",
    "bounded_terminal": "C42_STATE_RULE_BOUNDED_TERMINAL",
    "bounded_service": "C42_STATE_RULE_BOUNDED_SERVICE",
}
OPERATOR_KINDS = {
    "field_corrupt": "C42_STATE_OPERATOR_FIELD_CORRUPT",
    "field_required_zero_violation":
        "C42_STATE_OPERATOR_REQUIRED_ZERO_VIOLATION",
    "field_required_omission": "C42_STATE_OPERATOR_REQUIRED_OMISSION",
    "field_stale_key": "C42_STATE_OPERATOR_STALE_KEY",
    "field_invalid_enum": "C42_STATE_OPERATOR_INVALID_ENUM",
    "identity_edge_split": "C42_STATE_OPERATOR_IDENTITY_SPLIT",
    "identity_domain_collapse": "C42_STATE_OPERATOR_DOMAIN_COLLAPSE",
    "transition_skip": "C42_STATE_OPERATOR_TRANSITION_SKIP",
    "transition_stall": "C42_STATE_OPERATOR_TRANSITION_STALL",
    "transition_duplicate": "C42_STATE_OPERATOR_TRANSITION_DUPLICATE",
    "transition_early_terminal": "C42_STATE_OPERATOR_EARLY_TERMINAL",
    "transition_late_terminal": "C42_STATE_OPERATOR_LATE_TERMINAL",
}


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render(model_dir: Path) -> tuple[str, int, int, str]:
    model = build_model(model_dir)
    nodes = {
        (str(node["model_kind"]), str(node["id"])): node
        for node in model["nodes"]
        if node.get("model_kind") in {"identity", "phase"}
    }
    obligations = [
        obligation for obligation in model["obligations"]
        if obligation.get("model_kind") in {"identity", "phase"}
    ]
    digest = hashlib.sha256()
    groups: dict[tuple[object, ...], list[str]] = defaultdict(list)
    normalized: list[tuple[dict[str, object], dict[str, object]]] = []
    for obligation in obligations:
        digest.update(str(obligation["id"]).encode("utf-8"))
        digest.update(b"\0")
        key = (str(obligation["model_kind"]), str(obligation["node_id"]))
        node = nodes.get(key)
        if node is None:
            raise ModelError(f"state obligation node absent: {key}")
        target = str(node.get("target_kind"))
        rule = str(node.get("rule_kind"))
        operator = str(obligation["operator_id"])
        if target not in TARGET_KINDS or rule not in RULE_KINDS or \
                operator not in OPERATOR_KINDS:
            raise ModelError(
                f"unsupported state stimulus: {target}/{rule}/{operator}"
            )
        element = int(obligation["element_index"])
        element_count = int(node.get("element_count", 1))
        if element >= element_count:
            raise ModelError(f"state element exceeds node: {obligation['id']}")
        groups[(key, str(obligation["semantic_case_id"]), operator, element)].append(
            str(obligation["id"])
        )
        normalized.append((obligation, node))
    lines = [
        "/* Generated by gen_c42_state_obligations.py; do not edit. */\n",
        f"#define C42_STATE_MODEL_INPUT_DIGEST {c_string(str(model['input_digest']))}\n",
        f"#define C42_STATE_OBLIGATION_SET_SHA256 {c_string(digest.hexdigest())}\n",
        f"#define C42_STATE_OBLIGATION_COUNT {len(obligations)}u\n",
        f"#define C42_STATE_PROBE_COUNT {len(groups)}u\n",
        "static const struct c42_state_obligation_stimulus "
        "c42_state_obligations[C42_STATE_OBLIGATION_COUNT] = {\n",
    ]
    for obligation, node in normalized:
        element = int(obligation["element_index"])
        lines.extend([
            "    {\n",
            f"        {c_string(str(obligation['id']))},\n",
            f"        {c_string(str(obligation['node_id']))},\n",
            f"        {TARGET_KINDS[str(node['target_kind'])]},\n",
            f"        {RULE_KINDS[str(node['rule_kind'])]},\n",
            f"        {OPERATOR_KINDS[str(obligation['operator_id'])]},\n",
            f"        {int(node.get('element_count', 1))}u,\n",
            f"        {('UINT32_MAX' if element < 0 else str(element) + 'u')},\n",
            f"        {int(node.get('rank_m_before', 2))}u,\n",
            f"        {int(node.get('rank_m_after', 1))}u,\n",
            f"        {int(node.get('maximum_work_units', 0))}u\n",
            "    },\n",
        ])
    lines.append("};\n")
    return "".join(lines), len(obligations), len(groups), digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-dir", type=Path, default=DEFAULT_MODEL_DIR)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        rendered, obligations, probes, digest = render(arguments.model_dir)
        if arguments.check:
            if not arguments.output.is_file() or \
                    arguments.output.read_text(encoding="utf-8") != rendered:
                raise ModelError("state obligation stimulus differs")
        else:
            arguments.output.parent.mkdir(parents=True, exist_ok=True)
            arguments.output.write_text(rendered, encoding="utf-8")
    except (ModelError, OSError, UnicodeError) as error:
        print(f"C4.2 state obligation generator: FAIL: {error}", file=sys.stderr)
        return 1
    print(
        "C4.2 state obligation generator: PASS "
        f"obligations={obligations} probes={probes} set={digest}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
