#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Evanshenf
# SPDX-License-Identifier: BSD-3-Clause

"""Emit provider-obligation stimuli for the independent C provider executor."""

from __future__ import annotations

import argparse
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import sys

from check_c42_claim_models import DEFAULT_MODEL_DIR, ModelError, build_model


TARGET_KINDS = {
    "field": "C42_PROVIDER_TARGET_FIELD",
    "entrypoint": "C42_PROVIDER_TARGET_ENTRYPOINT",
    "relation": "C42_PROVIDER_TARGET_RELATION",
    "effect": "C42_PROVIDER_TARGET_EFFECT",
    "response_order": "C42_PROVIDER_TARGET_RESPONSE_ORDER",
}

RULE_KINDS = {
    "exact": "C42_PROVIDER_RULE_EXACT",
    "conditional": "C42_PROVIDER_RULE_CONDITIONAL",
    "required_zero": "C42_PROVIDER_RULE_REQUIRED_ZERO",
    "preserve": "C42_PROVIDER_RULE_PRESERVE",
    "start": "C42_PROVIDER_RULE_START",
    "query": "C42_PROVIDER_RULE_QUERY",
    "action": "C42_PROVIDER_RULE_ACTION",
    "equal": "C42_PROVIDER_RULE_EQUAL",
    "derived_equal": "C42_PROVIDER_RULE_DERIVED_EQUAL",
    "strictly_monotonic": "C42_PROVIDER_RULE_STRICTLY_MONOTONIC",
    "committed": "C42_PROVIDER_RULE_COMMITTED",
    "idempotent": "C42_PROVIDER_RULE_IDEMPOTENT",
    "returned": "C42_PROVIDER_RULE_RETURNED",
    "lost_before_effect": "C42_PROVIDER_RULE_LOST_BEFORE",
    "lost_after_effect": "C42_PROVIDER_RULE_LOST_AFTER",
}

OPERATOR_KINDS = {
    "field_corrupt": "C42_PROVIDER_OPERATOR_FIELD_CORRUPT",
    "field_required_zero_violation":
        "C42_PROVIDER_OPERATOR_REQUIRED_ZERO_VIOLATION",
    "field_required_omission": "C42_PROVIDER_OPERATOR_REQUIRED_OMISSION",
    "field_stale_key": "C42_PROVIDER_OPERATOR_STALE_KEY",
    "field_invalid_enum": "C42_PROVIDER_OPERATOR_INVALID_ENUM",
    "entrypoint_call_kind_substitute":
        "C42_PROVIDER_OPERATOR_CALL_KIND_SUBSTITUTE",
    "field_preserve_overwrite": "C42_PROVIDER_OPERATOR_PRESERVE_OVERWRITE",
    "relation_split": "C42_PROVIDER_OPERATOR_RELATION_SPLIT",
    "relation_stall": "C42_PROVIDER_OPERATOR_RELATION_STALL",
    "effect_skip": "C42_PROVIDER_OPERATOR_EFFECT_SKIP",
    "effect_duplicate": "C42_PROVIDER_OPERATOR_EFFECT_DUPLICATE",
    "response_order_swap": "C42_PROVIDER_OPERATOR_RESPONSE_ORDER_SWAP",
}


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render(model_dir: Path) -> str:
    model = build_model(model_dir)
    nodes = {
        str(node["id"]): node for node in model["nodes"]
        if node.get("model_kind") == "provider"
    }
    obligations = [
        obligation for obligation in model["obligations"]
        if obligation.get("model_kind") == "provider"
    ]
    obligation_set_digest = hashlib.sha256()
    for obligation in obligations:
        obligation_set_digest.update(str(obligation["id"]).encode("utf-8"))
        obligation_set_digest.update(b"\0")
    probe_groups: dict[tuple[object, ...], list[str]] = defaultdict(list)
    lines: list[str] = [
        "/* Generated by gen_c42_provider_obligations.py; do not edit. */\n",
        f"#define C42_PROVIDER_MODEL_INPUT_DIGEST {c_string(str(model['input_digest']))}\n",
        "#define C42_PROVIDER_OBLIGATION_SET_SHA256 "
        f"{c_string(obligation_set_digest.hexdigest())}\n",
        f"#define C42_PROVIDER_OBLIGATION_COUNT {len(obligations)}u\n",
    ]
    normalized: list[tuple[dict[str, object], dict[str, object]]] = []
    for obligation in obligations:
        node_id = str(obligation["node_id"])
        node = nodes.get(node_id)
        if node is None:
            raise ModelError(f"provider obligation has no provider node: {node_id}")
        target = str(node.get("target_kind"))
        rule = str(node.get("rule_kind"))
        operator = str(obligation["operator_id"])
        if target not in TARGET_KINDS:
            raise ModelError(f"unsupported provider target kind: {target}")
        if rule not in RULE_KINDS:
            raise ModelError(f"unsupported provider rule kind: {rule}")
        if operator not in OPERATOR_KINDS:
            raise ModelError(f"unsupported provider operator: {operator}")
        element = int(obligation["element_index"])
        element_count = int(node.get("element_count", 1))
        if element >= element_count:
            raise ModelError(f"provider element exceeds node width: {obligation['id']}")
        key = (
            node_id, str(obligation["semantic_case_id"]), operator, element,
        )
        probe_groups[key].append(str(obligation["id"]))
        normalized.append((obligation, node))
    lines.append(f"#define C42_PROVIDER_PROBE_COUNT {len(probe_groups)}u\n")
    lines.append(
        "static const struct c42_provider_obligation_stimulus "
        "c42_provider_obligations[C42_PROVIDER_OBLIGATION_COUNT] = {\n"
    )
    for obligation, node in normalized:
        element = int(obligation["element_index"])
        lines.extend([
            "    {\n",
            f"        {c_string(str(obligation['id']))},\n",
            f"        {c_string(str(obligation['node_id']))},\n",
            f"        {TARGET_KINDS[str(node['target_kind'])]},\n",
            f"        {RULE_KINDS[str(node['rule_kind'])]},\n",
            f"        {OPERATOR_KINDS[str(obligation['operator_id'])]},\n",
            f"        {int(node.get('element_count', 1))}u,\n",
            f"        {('UINT32_MAX' if element < 0 else str(element) + 'u')}\n",
            "    },\n",
        ])
    lines.append("};\n")
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-dir", type=Path, default=DEFAULT_MODEL_DIR)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        rendered = render(arguments.model_dir)
        if arguments.check:
            if not arguments.output.is_file() or \
                    arguments.output.read_text(encoding="utf-8") != rendered:
                raise ModelError("provider obligation stimulus differs")
        else:
            arguments.output.parent.mkdir(parents=True, exist_ok=True)
            arguments.output.write_text(rendered, encoding="utf-8")
    except (ModelError, OSError, UnicodeError) as error:
        print(f"C4.2 provider obligation generator: FAIL: {error}", file=sys.stderr)
        return 1
    model = build_model(arguments.model_dir)
    provider = [
        obligation for obligation in model["obligations"]
        if obligation.get("model_kind") == "provider"
    ]
    probes = {
        (
            str(obligation["node_id"]),
            str(obligation["semantic_case_id"]),
            str(obligation["operator_id"]),
            int(obligation["element_index"]),
        )
        for obligation in provider
    }
    print(
        "C4.2 provider obligation generator: PASS "
        f"obligations={len(provider)} probes={len(probes)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
